name: superfitbuddy
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.0 # Upgrade to version compatible with cloud_firestore
  cloud_firestore: ^5.5.0 # Keep the latest compatible version
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  flutter_map: ^4.0.0
  flutter_map_marker_popup: ^5.1.0
  latlong2: ^0.8.1
  firebase_auth: ^5.3.3
  google_maps_flutter: ^2.2.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  intl: ^0.18.0
  latlong2: ^0.8.1

flutter:
  uses-material-design: true
