name: superfitbuddy
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.0 # Upgrade to version compatible with cloud_firestore
  cloud_firestore: ^5.5.0 # Keep the latest compatible version
  geocoding: ^3.0.0
  geolocator: ^13.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
